"""initial_schema

Revision ID: 914b3d47d408
Revises: 
Create Date: 2026-07-18 11:18:55.564434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import cbms_api


# revision identifiers, used by Alembic.
revision: str = '914b3d47d408'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', cbms_api.database.models.SafeUUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', cbms_api.database.models.SafeUUID(length=36), nullable=False),
    sa.Column('organization_id', cbms_api.database.models.SafeUUID(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plant_profiles',
    sa.Column('id', cbms_api.database.models.SafeUUID(length=36), nullable=False),
    sa.Column('organization_id', cbms_api.database.models.SafeUUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('boiler_type', sa.String(length=100), nullable=False),
    sa.Column('exhaust_flow_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('baseline_temperature', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('co2_concentration', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('so2_concentration', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('fly_ash_load', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('nox_concentration', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('extended_config', cbms_api.database.models.SafeJSONB(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_plant_profiles_org', 'plant_profiles', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('id', cbms_api.database.models.SafeUUID(length=36), nullable=False),
    sa.Column('organization_id', cbms_api.database.models.SafeUUID(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('roles', cbms_api.database.models.SafeJSONB(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=100), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('logistics_configs',
    sa.Column('id', cbms_api.database.models.SafeUUID(length=36), nullable=False),
    sa.Column('plant_profile_id', cbms_api.database.models.SafeUUID(length=36), nullable=False),
    sa.Column('water_cost_per_kl', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('electricity_cost_per_kwh', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('chitosan_cost_per_kg', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('calcium_source_type', sa.String(length=100), nullable=False),
    sa.Column('calcium_cost_per_ton', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('local_brick_market_value', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('ccts_credit_price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['plant_profile_id'], ['plant_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_profile_id')
    )
    op.create_table('mfa_secrets',
    sa.Column('user_id', cbms_api.database.models.SafeUUID(length=36), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('backup_codes', cbms_api.database.models.SafeJSONB(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', cbms_api.database.models.SafeUUID(length=36), nullable=False),
    sa.Column('user_id', cbms_api.database.models.SafeUUID(length=36), nullable=False),
    sa.Column('organization_id', cbms_api.database.models.SafeUUID(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('token_family', sa.String(length=255), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('simulation_runs',
    sa.Column('id', cbms_api.database.models.SafeUUID(length=36), nullable=False),
    sa.Column('organization_id', cbms_api.database.models.SafeUUID(length=36), nullable=False),
    sa.Column('plant_profile_id', cbms_api.database.models.SafeUUID(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('press_force_bar', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('enzyme_concentration_mg_l', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('chitosan_wt_pct', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('pdf_report_url', sa.String(length=512), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('parameter_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plant_profile_id'], ['plant_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sim_runs_org', 'simulation_runs', ['organization_id'], unique=False)
    op.create_index('idx_sim_runs_plant', 'simulation_runs', ['plant_profile_id'], unique=False)
    op.create_table('generated_reports',
    sa.Column('id', cbms_api.database.models.SafeUUID(length=36), nullable=False),
    sa.Column('organization_id', cbms_api.database.models.SafeUUID(length=36), nullable=False),
    sa.Column('simulation_run_id', cbms_api.database.models.SafeUUID(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('worker_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_results',
    sa.Column('id', cbms_api.database.models.SafeUUID(length=36), nullable=False),
    sa.Column('simulation_run_id', cbms_api.database.models.SafeUUID(length=36), nullable=False),
    sa.Column('co2_capture_efficiency_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('so2_capture_efficiency_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('predicted_block_strength_mpa', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('block_grade', sa.String(length=100), nullable=False),
    sa.Column('hourly_block_yield_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('annual_block_count', sa.Integer(), nullable=False),
    sa.Column('estimated_opex_per_ton_co2', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('annual_ccts_revenue_inr', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('annual_block_revenue_inr', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('annual_opex_inr', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('annual_net_revenue_inr', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('capex_total_inr', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('simple_payback_months', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('npv_10yr_inr', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('irr_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('mean_saturation_time_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('p95_saturation_time_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('cpcb_compliant', sa.Boolean(), nullable=False),
    sa.Column('uq_metrics', cbms_api.database.models.SafeJSONB(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulation_run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_results')
    op.drop_table('generated_reports')
    op.drop_index('idx_sim_runs_plant', table_name='simulation_runs')
    op.drop_index('idx_sim_runs_org', table_name='simulation_runs')
    op.drop_table('simulation_runs')
    op.drop_table('refresh_tokens')
    op.drop_table('mfa_secrets')
    op.drop_table('logistics_configs')
    op.drop_table('users')
    op.drop_index('idx_plant_profiles_org', table_name='plant_profiles')
    op.drop_table('plant_profiles')
    op.drop_table('audit_events')
    op.drop_table('organizations')
    # ### end Alembic commands ###
